"""add_materials_and_products

Revision ID: 74cb7ab0e456
Revises: 0001_initial_users
Create Date: 2026-02-27 16:54:15.245696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cb7ab0e456'
down_revision: Union[str, None] = '0001_initial_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('price_quantity', sa.Float(), nullable=False),
    sa.Column('market_price_per_unit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_user_id'), 'materials', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('batch_output_quantity', sa.Float(), nullable=False),
    sa.Column('packaging_cost_per_unit', sa.Float(), nullable=False),
    sa.Column('margin_percentage', sa.Float(), nullable=False),
    sa.Column('total_material_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('final_cost_per_unit', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('material_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('price_quantity', sa.Float(), nullable=False),
    sa.Column('market_price_per_unit', sa.Float(), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.Column('line_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_snapshots_id'), 'material_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_material_snapshots_product_id'), 'material_snapshots', ['product_id'], unique=False)
    op.create_table('product_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('quantity_str', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_entries_id'), 'product_entries', ['id'], unique=False)
    op.create_index(op.f('ix_product_entries_product_id'), 'product_entries', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_entries_product_id'), table_name='product_entries')
    op.drop_index(op.f('ix_product_entries_id'), table_name='product_entries')
    op.drop_table('product_entries')
    op.drop_index(op.f('ix_material_snapshots_product_id'), table_name='material_snapshots')
    op.drop_index(op.f('ix_material_snapshots_id'), table_name='material_snapshots')
    op.drop_table('material_snapshots')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_materials_user_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
